name = "sofya"
license = "MIT"
licenselink = "http://opensource.org/licenses/MIT"
description = "A minimalist theme for Hugo."
homepage = "https://github.com/jonathondilworth/sofya"
tags = ["minimal", "blog"]
features = ["menu", "icons"]

[author]
  name = "Jonathon Dilworth"
  homepage = "http://dilworth.me/"